- name: install apache and php for Ubuntu servers
  tags: apache,apache2,ubuntu  
  package:
    name: 
      - "{{ apache_package }}"
      - "{{ php_package }}"
    state: latest
    update_cache: yes

- name: copy default html file forsite
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
